name: 'Deploy PodOS App'
description: 'Builds and deploys a PodOS app to Netlify'
inputs:
  app-name:
    description: 'Name of the app to build and deploy'
    required: true
  netlify-flags:
    description: 'Additional flags to pass to netlify-cli deploy command'
    required: false
    default: ''
  netlify-site-id:
    description: 'Netlify Site ID'
    required: true
  netlify-auth-token:
    description: 'Netlify Auth Token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Echo Version
      shell: bash
      run: echo release ${{ inputs.app-name }} to Netlify site ${{ inputs.netlify-site-id }} based on @pod-os/elements version ${POD_OS_ELEMENTS_VERSION}

    - name: Build PodOS App
      working-directory: ./apps
      shell: bash
      run: make ${{ inputs.app-name }}

    - name: Deploy PodOS App
      working-directory: ./apps
      shell: bash
      run: npx netlify-cli deploy --dir=dist/${{ inputs.app-name }} ${{ inputs.netlify-flags }}
      env:
        NETLIFY_SITE_ID: ${{ inputs.netlify-site-id }}
        NETLIFY_AUTH_TOKEN: ${{ inputs.netlify-auth-token }}
