name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      version:
        description: Which version to deploy

jobs:

  deploy-pod-os-apps:
    runs-on: ubuntu-latest
    env:
      POD_OS_ELEMENTS_VERSION: ${{ github.event.inputs.version }}
    steps:
      - run: echo release apps based on @pod-os/elements version ${POD_OS_ELEMENTS_VERSION}
      - uses: actions/checkout@v3
      - name: Build PodOS Browser
        working-directory: ./apps
        run: make pos-app-browser
      - name: Deploy PodOS Browser
        working-directory: ./apps
        run: npx netlify-cli deploy --site=pod-os-browser --dir=dist/pos-app-browser --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_POD_OS_BROWSER_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
